name: Notificación ntfy

on:
  push:
    branches:
      - main

jobs:
  send_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Enviar notificación a ntfy.sh
        run: |
          curl -sS -X POST \
            -H "Title: Nuevo push en main" \
            -d "Se subió código nuevo al repositorio hola-mundo-devops" \
            https://ntfy.sh/devops-itla
